/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.lista.view;

import br.com.lista.util.ConnectionFactory;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author user
 */
public class PesquisaLista extends javax.swing.JFrame {

    private DefaultTableModel model;
    public PesquisaLista() {
         super("Listagem de Fornecedores");
        initComponents();
        carregarDadosTabela();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLista = new javax.swing.JTable();
        lbProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));

        tabelaLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EMPRESA", "FORMA", "MARCA", "WEB SITE", "PRODUTO"
            }
        ));
        jScrollPane1.setViewportView(tabelaLista);

        lbProduto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbProduto.setText("PRODUTO");

        txtProduto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtProduto.setMargin(new java.awt.Insets(5, 2, 2, 2));
        txtProduto.setPreferredSize(new java.awt.Dimension(6, 23));
        txtProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdutoKeyPressed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        jLabel1.setText("190112.02");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbProduto)
                .addGap(33, 33, 33)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(474, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(lbProduto))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
       txtProduto.setText("");
        
    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoKeyPressed
        model = (DefaultTableModel) tabelaLista.getModel();
       TableRowSorter sorter = new TableRowSorter<TableModel>(model);
       tabelaLista.setRowSorter(sorter);
       
       String produto = txtProduto.getText();
       if(produto != null){
           sorter.setRowFilter(RowFilter.regexFilter(("(?i)")+produto));
       }else{
           sorter.setRowFilter(null);
       }
    }//GEN-LAST:event_txtProdutoKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PesquisaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbProduto;
    private javax.swing.JTable tabelaLista;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables

  private void carregarDadosTabela(){
        String sql = " select empresa, forma, marca,website, produtos from ox_lista_forn order by id";
        
        try{
            
            Connection connectio = ConnectionFactory.getConexao();
            PreparedStatement ps = connectio.prepareStatement(sql);
            
            ResultSet rs = ps.executeQuery();
            
            tabelaLista.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            
            tabelaLista.getColumnModel().getColumn(0).setPreferredWidth(120);
            tabelaLista.getColumnModel().getColumn(1).setPreferredWidth(100);
            tabelaLista.getColumnModel().getColumn(2).setPreferredWidth(150);
            tabelaLista.getColumnModel().getColumn(3).setPreferredWidth(200);
            tabelaLista.getColumnModel().getColumn(4).setPreferredWidth(310);
            tabelaLista.getRowHeight(100);
            
            
            
            model = (DefaultTableModel) tabelaLista.getModel();
            
            while(rs.next()){
               // Integer rsId = rs.getInt("id");
                String rsEmpresa = rs.getString("empresa");
                String rsForma = rs.getString("forma");
                String rsMarca = rs.getString("marca");
                String rsWebSite = rs.getString("website");
                String rsProduto = rs.getString("produtos");
                //preencher os dado na JTable que estão retornando do banco de dados
                model.addRow(new Object[]{rsEmpresa, rsForma, rsMarca,  rsWebSite,rsProduto});
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
}
